//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.18408
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CAFT {
    
    
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.VisualStudio.Editors.SettingsDesigner.SettingsSingleFileGenerator", "12.0.0.0")]
    internal sealed partial class CaftSettings : global::System.Configuration.ApplicationSettingsBase {
        
        private static CaftSettings defaultInstance = ((CaftSettings)(global::System.Configuration.ApplicationSettingsBase.Synchronized(new CaftSettings())));
        
        public static CaftSettings Default {
            get {
                return defaultInstance;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("0.2")]
        public decimal TimeStamp {
            get {
                return ((decimal)(this["TimeStamp"]));
            }
            set {
                this["TimeStamp"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("300")]
        public int GridRowCount {
            get {
                return ((int)(this["GridRowCount"]));
            }
            set {
                this["GridRowCount"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("True")]
        public bool LaneSignal {
            get {
                return ((bool)(this["LaneSignal"]));
            }
            set {
                this["LaneSignal"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("0.5")]
        public decimal CellSize_Height {
            get {
                return ((decimal)(this["CellSize_Height"]));
            }
            set {
                this["CellSize_Height"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("1")]
        public decimal TwoVhSize_Column {
            get {
                return ((decimal)(this["TwoVhSize_Column"]));
            }
            set {
                this["TwoVhSize_Column"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("2")]
        public decimal TwoVhSize_Row {
            get {
                return ((decimal)(this["TwoVhSize_Row"]));
            }
            set {
                this["TwoVhSize_Row"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("2")]
        public decimal ThreeVhSize_Column {
            get {
                return ((decimal)(this["ThreeVhSize_Column"]));
            }
            set {
                this["ThreeVhSize_Column"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("2")]
        public decimal ThreeVhSize_Row {
            get {
                return ((decimal)(this["ThreeVhSize_Row"]));
            }
            set {
                this["ThreeVhSize_Row"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("3")]
        public decimal FourVhSize_Row {
            get {
                return ((decimal)(this["FourVhSize_Row"]));
            }
            set {
                this["FourVhSize_Row"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("2")]
        public decimal FourVhSize_Column {
            get {
                return ((decimal)(this["FourVhSize_Column"]));
            }
            set {
                this["FourVhSize_Column"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("2")]
        public decimal LCV1VhSize_Column {
            get {
                return ((decimal)(this["LCV1VhSize_Column"]));
            }
            set {
                this["LCV1VhSize_Column"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("3")]
        public decimal LCV1VhSize_Row {
            get {
                return ((decimal)(this["LCV1VhSize_Row"]));
            }
            set {
                this["LCV1VhSize_Row"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("3")]
        public decimal TwoVh_MaxAcceleration {
            get {
                return ((decimal)(this["TwoVh_MaxAcceleration"]));
            }
            set {
                this["TwoVh_MaxAcceleration"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("3")]
        public decimal ThreeVh_MaxAcceleration {
            get {
                return ((decimal)(this["ThreeVh_MaxAcceleration"]));
            }
            set {
                this["ThreeVh_MaxAcceleration"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("3")]
        public decimal FourVh_MaxAcceleration {
            get {
                return ((decimal)(this["FourVh_MaxAcceleration"]));
            }
            set {
                this["FourVh_MaxAcceleration"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("3")]
        public decimal LCV1Vh_MaxAcceleration {
            get {
                return ((decimal)(this["LCV1Vh_MaxAcceleration"]));
            }
            set {
                this["LCV1Vh_MaxAcceleration"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("4")]
        public decimal Vh_OvertakingGap {
            get {
                return ((decimal)(this["Vh_OvertakingGap"]));
            }
            set {
                this["Vh_OvertakingGap"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("10")]
        public decimal Vh_AccelerationGap {
            get {
                return ((decimal)(this["Vh_AccelerationGap"]));
            }
            set {
                this["Vh_AccelerationGap"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("0.5")]
        public decimal CellSize_Width {
            get {
                return ((decimal)(this["CellSize_Width"]));
            }
            set {
                this["CellSize_Width"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("20")]
        public decimal CellSize_InPixels {
            get {
                return ((decimal)(this["CellSize_InPixels"]));
            }
            set {
                this["CellSize_InPixels"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("60")]
        public decimal headway {
            get {
                return ((decimal)(this["headway"]));
            }
            set {
                this["headway"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("4")]
        public decimal LCV2VhSize_Row {
            get {
                return ((decimal)(this["LCV2VhSize_Row"]));
            }
            set {
                this["LCV2VhSize_Row"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("2")]
        public decimal LCV2VhSize_Column {
            get {
                return ((decimal)(this["LCV2VhSize_Column"]));
            }
            set {
                this["LCV2VhSize_Column"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("2")]
        public decimal LCV2Vh_MaxAcceleration {
            get {
                return ((decimal)(this["LCV2Vh_MaxAcceleration"]));
            }
            set {
                this["LCV2Vh_MaxAcceleration"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("5")]
        public decimal HCV1VhSize_Row {
            get {
                return ((decimal)(this["HCV1VhSize_Row"]));
            }
            set {
                this["HCV1VhSize_Row"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("2")]
        public decimal HCV1VhSize_Column {
            get {
                return ((decimal)(this["HCV1VhSize_Column"]));
            }
            set {
                this["HCV1VhSize_Column"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("1")]
        public decimal HCV1Vh_MaxAcceleration {
            get {
                return ((decimal)(this["HCV1Vh_MaxAcceleration"]));
            }
            set {
                this["HCV1Vh_MaxAcceleration"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("6")]
        public decimal HCV2VhSize_Row {
            get {
                return ((decimal)(this["HCV2VhSize_Row"]));
            }
            set {
                this["HCV2VhSize_Row"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("2")]
        public decimal HCV2VhSize_Column {
            get {
                return ((decimal)(this["HCV2VhSize_Column"]));
            }
            set {
                this["HCV2VhSize_Column"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("1")]
        public decimal HCV2Vh_MaxAcceleration {
            get {
                return ((decimal)(this["HCV2Vh_MaxAcceleration"]));
            }
            set {
                this["HCV2Vh_MaxAcceleration"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("40")]
        public decimal TwoVh_MaxAccelerationInKm {
            get {
                return ((decimal)(this["TwoVh_MaxAccelerationInKm"]));
            }
            set {
                this["TwoVh_MaxAccelerationInKm"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("35")]
        public decimal ThreeVh_MaxAccelerationInKm {
            get {
                return ((decimal)(this["ThreeVh_MaxAccelerationInKm"]));
            }
            set {
                this["ThreeVh_MaxAccelerationInKm"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("60")]
        public decimal FourVh_MaxAccelerationInKm {
            get {
                return ((decimal)(this["FourVh_MaxAccelerationInKm"]));
            }
            set {
                this["FourVh_MaxAccelerationInKm"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("50")]
        public decimal LCV1Vh_MaxAccelerationInKm {
            get {
                return ((decimal)(this["LCV1Vh_MaxAccelerationInKm"]));
            }
            set {
                this["LCV1Vh_MaxAccelerationInKm"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("40")]
        public decimal LCV2Vh_MaxAccelerationInKm {
            get {
                return ((decimal)(this["LCV2Vh_MaxAccelerationInKm"]));
            }
            set {
                this["LCV2Vh_MaxAccelerationInKm"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("30")]
        public decimal HCV1Vh_MaxAccelerationInKm {
            get {
                return ((decimal)(this["HCV1Vh_MaxAccelerationInKm"]));
            }
            set {
                this["HCV1Vh_MaxAccelerationInKm"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("30")]
        public decimal HCV2Vh_MaxAccelerationInKm {
            get {
                return ((decimal)(this["HCV2Vh_MaxAccelerationInKm"]));
            }
            set {
                this["HCV2Vh_MaxAccelerationInKm"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("100")]
        public int BumpLine {
            get {
                return ((int)(this["BumpLine"]));
            }
            set {
                this["BumpLine"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("0")]
        public int TwoVhAccParam {
            get {
                return ((int)(this["TwoVhAccParam"]));
            }
            set {
                this["TwoVhAccParam"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("0")]
        public int ThreeVhAccParam {
            get {
                return ((int)(this["ThreeVhAccParam"]));
            }
            set {
                this["ThreeVhAccParam"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("0")]
        public int FourVhAccParam {
            get {
                return ((int)(this["FourVhAccParam"]));
            }
            set {
                this["FourVhAccParam"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("0")]
        public int LCV1VhAccParam {
            get {
                return ((int)(this["LCV1VhAccParam"]));
            }
            set {
                this["LCV1VhAccParam"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("0")]
        public int LCV2VhAccParam {
            get {
                return ((int)(this["LCV2VhAccParam"]));
            }
            set {
                this["LCV2VhAccParam"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("0")]
        public int HCV1VhAccParam {
            get {
                return ((int)(this["HCV1VhAccParam"]));
            }
            set {
                this["HCV1VhAccParam"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("0")]
        public int HCV2VhAccParam {
            get {
                return ((int)(this["HCV2VhAccParam"]));
            }
            set {
                this["HCV2VhAccParam"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("10")]
        public decimal TwoVhAccParamInkm {
            get {
                return ((decimal)(this["TwoVhAccParamInkm"]));
            }
            set {
                this["TwoVhAccParamInkm"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("10")]
        public decimal ThreeVhAccParamInkm {
            get {
                return ((decimal)(this["ThreeVhAccParamInkm"]));
            }
            set {
                this["ThreeVhAccParamInkm"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("10")]
        public decimal FourVhAccParamInkm {
            get {
                return ((decimal)(this["FourVhAccParamInkm"]));
            }
            set {
                this["FourVhAccParamInkm"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("10")]
        public decimal LCV1VhAccParamInkm {
            get {
                return ((decimal)(this["LCV1VhAccParamInkm"]));
            }
            set {
                this["LCV1VhAccParamInkm"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("10")]
        public decimal LCV2VhAccParamInkm {
            get {
                return ((decimal)(this["LCV2VhAccParamInkm"]));
            }
            set {
                this["LCV2VhAccParamInkm"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("10")]
        public decimal HCV1VhAccParamInkm {
            get {
                return ((decimal)(this["HCV1VhAccParamInkm"]));
            }
            set {
                this["HCV1VhAccParamInkm"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("10")]
        public decimal HCV2VhAccParamInkm {
            get {
                return ((decimal)(this["HCV2VhAccParamInkm"]));
            }
            set {
                this["HCV2VhAccParamInkm"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("True")]
        public bool TwoVhInclude {
            get {
                return ((bool)(this["TwoVhInclude"]));
            }
            set {
                this["TwoVhInclude"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("True")]
        public bool ThreeVhInclude {
            get {
                return ((bool)(this["ThreeVhInclude"]));
            }
            set {
                this["ThreeVhInclude"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("True")]
        public bool FourVhInclude {
            get {
                return ((bool)(this["FourVhInclude"]));
            }
            set {
                this["FourVhInclude"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("True")]
        public bool LCV1VhInclude {
            get {
                return ((bool)(this["LCV1VhInclude"]));
            }
            set {
                this["LCV1VhInclude"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("False")]
        public bool LCV2VhInclude {
            get {
                return ((bool)(this["LCV2VhInclude"]));
            }
            set {
                this["LCV2VhInclude"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("True")]
        public bool HCV1VhInclude {
            get {
                return ((bool)(this["HCV1VhInclude"]));
            }
            set {
                this["HCV1VhInclude"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("False")]
        public bool HCV2VhInclude {
            get {
                return ((bool)(this["HCV2VhInclude"]));
            }
            set {
                this["HCV2VhInclude"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("True")]
        public bool bumpInclude {
            get {
                return ((bool)(this["bumpInclude"]));
            }
            set {
                this["bumpInclude"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("20")]
        public int bumpArea {
            get {
                return ((int)(this["bumpArea"]));
            }
            set {
                this["bumpArea"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("False")]
        public bool signalInclude {
            get {
                return ((bool)(this["signalInclude"]));
            }
            set {
                this["signalInclude"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("20")]
        public int GreenSignalTime {
            get {
                return ((int)(this["GreenSignalTime"]));
            }
            set {
                this["GreenSignalTime"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("20")]
        public int RedSignalTime {
            get {
                return ((int)(this["RedSignalTime"]));
            }
            set {
                this["RedSignalTime"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("0")]
        public int AmberSignalTime {
            get {
                return ((int)(this["AmberSignalTime"]));
            }
            set {
                this["AmberSignalTime"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("False")]
        public bool AutoSignalInclude {
            get {
                return ((bool)(this["AutoSignalInclude"]));
            }
            set {
                this["AutoSignalInclude"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("20")]
        public int AutoGreenSignalTime_Bottom {
            get {
                return ((int)(this["AutoGreenSignalTime_Bottom"]));
            }
            set {
                this["AutoGreenSignalTime_Bottom"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("20")]
        public int AutoRedSignalTime {
            get {
                return ((int)(this["AutoRedSignalTime"]));
            }
            set {
                this["AutoRedSignalTime"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("False")]
        public bool lefttraffic {
            get {
                return ((bool)(this["lefttraffic"]));
            }
            set {
                this["lefttraffic"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("False")]
        public bool righttraffic {
            get {
                return ((bool)(this["righttraffic"]));
            }
            set {
                this["righttraffic"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("False")]
        public bool toptraffic {
            get {
                return ((bool)(this["toptraffic"]));
            }
            set {
                this["toptraffic"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("True")]
        public bool bottomtraffic {
            get {
                return ((bool)(this["bottomtraffic"]));
            }
            set {
                this["bottomtraffic"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("10")]
        public int AutoGreenSignalTime_Left {
            get {
                return ((int)(this["AutoGreenSignalTime_Left"]));
            }
            set {
                this["AutoGreenSignalTime_Left"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("20")]
        public int AutoGreenSignalTime_Top {
            get {
                return ((int)(this["AutoGreenSignalTime_Top"]));
            }
            set {
                this["AutoGreenSignalTime_Top"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("10")]
        public int AutoGreenSignalTime_Right {
            get {
                return ((int)(this["AutoGreenSignalTime_Right"]));
            }
            set {
                this["AutoGreenSignalTime_Right"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("False")]
        public bool vhRangeInclude {
            get {
                return ((bool)(this["vhRangeInclude"]));
            }
            set {
                this["vhRangeInclude"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("0")]
        public int VhRangeMin {
            get {
                return ((int)(this["VhRangeMin"]));
            }
            set {
                this["VhRangeMin"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("10")]
        public int VhRangeMax {
            get {
                return ((int)(this["VhRangeMax"]));
            }
            set {
                this["VhRangeMax"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("")]
        public string VhRangeTime {
            get {
                return ((string)(this["VhRangeTime"]));
            }
            set {
                this["VhRangeTime"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("40")]
        public int IntersectionSpeedZone {
            get {
                return ((int)(this["IntersectionSpeedZone"]));
            }
            set {
                this["IntersectionSpeedZone"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("7.2")]
        public decimal RoadWidth {
            get {
                return ((decimal)(this["RoadWidth"]));
            }
            set {
                this["RoadWidth"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("65")]
        public int percentTwoVh {
            get {
                return ((int)(this["percentTwoVh"]));
            }
            set {
                this["percentTwoVh"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("10")]
        public int percentThreeVh {
            get {
                return ((int)(this["percentThreeVh"]));
            }
            set {
                this["percentThreeVh"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("10")]
        public int percentFourVh {
            get {
                return ((int)(this["percentFourVh"]));
            }
            set {
                this["percentFourVh"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("0")]
        public int percentLCV1 {
            get {
                return ((int)(this["percentLCV1"]));
            }
            set {
                this["percentLCV1"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("0")]
        public int percentLCV2 {
            get {
                return ((int)(this["percentLCV2"]));
            }
            set {
                this["percentLCV2"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("0")]
        public int percentHCV1 {
            get {
                return ((int)(this["percentHCV1"]));
            }
            set {
                this["percentHCV1"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("0")]
        public int percentHCV2 {
            get {
                return ((int)(this["percentHCV2"]));
            }
            set {
                this["percentHCV2"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("50")]
        public int percentStraight {
            get {
                return ((int)(this["percentStraight"]));
            }
            set {
                this["percentStraight"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("30")]
        public int percentRight {
            get {
                return ((int)(this["percentRight"]));
            }
            set {
                this["percentRight"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("20")]
        public int percentLeft {
            get {
                return ((int)(this["percentLeft"]));
            }
            set {
                this["percentLeft"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("80")]
        public int DelayDistance {
            get {
                return ((int)(this["DelayDistance"]));
            }
            set {
                this["DelayDistance"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("49")]
        public int NoiseProbFactor {
            get {
                return ((int)(this["NoiseProbFactor"]));
            }
            set {
                this["NoiseProbFactor"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("4")]
        public int CrossRoadSignalAmberTime {
            get {
                return ((int)(this["CrossRoadSignalAmberTime"]));
            }
            set {
                this["CrossRoadSignalAmberTime"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("20")]
        public int GreenSignalTimeLeft {
            get {
                return ((int)(this["GreenSignalTimeLeft"]));
            }
            set {
                this["GreenSignalTimeLeft"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("20")]
        public int GreenSignalTimeTop {
            get {
                return ((int)(this["GreenSignalTimeTop"]));
            }
            set {
                this["GreenSignalTimeTop"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("20")]
        public int GreenSignalTimeRight {
            get {
                return ((int)(this["GreenSignalTimeRight"]));
            }
            set {
                this["GreenSignalTimeRight"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("1")]
        public int SignalFirstLegSelection {
            get {
                return ((int)(this["SignalFirstLegSelection"]));
            }
            set {
                this["SignalFirstLegSelection"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("10")]
        public int SecondsForHeadwayDist {
            get {
                return ((int)(this["SecondsForHeadwayDist"]));
            }
            set {
                this["SecondsForHeadwayDist"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("False")]
        public bool signalIncludePed {
            get {
                return ((bool)(this["signalIncludePed"]));
            }
            set {
                this["signalIncludePed"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("50")]
        public int SGreenSignalPed {
            get {
                return ((int)(this["SGreenSignalPed"]));
            }
            set {
                this["SGreenSignalPed"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("20")]
        public int SRedSignalPed {
            get {
                return ((int)(this["SRedSignalPed"]));
            }
            set {
                this["SRedSignalPed"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("3")]
        public int SAmberSignalPed {
            get {
                return ((int)(this["SAmberSignalPed"]));
            }
            set {
                this["SAmberSignalPed"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("150")]
        public int SignalLinePed {
            get {
                return ((int)(this["SignalLinePed"]));
            }
            set {
                this["SignalLinePed"] = value;
            }
        }
    }
}
